PREFIX ncit:<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX roo:<http://www.cancerdata.org/roo/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX icd:<http://purl.bioontology.org/ontology/ICD10/>
PREFIX uo:<http://purl.obolibrary.org/obo/>

SELECT *
WHERE {
	?patient rdf:type ncit:C16960.
	
	?patient roo:100018 ?genderObject.
	?genderObject rdf:type ncit:C28421.
	
	?patient roo:100020 ?disease.
	?disease rdf:type icd:C20.
	
	{ 
		?disease roo:100243 ?clinTNM.
		?clinTNM rdf:type ncit:C48881.
		?clinTNM roo:100244 ?clinTNMt.
		?clinTNMt rdf:type ?clinTStage.
		
		?clinTNM roo:100242 ?clinTNMn.
		?clinTNMn rdf:type ?clinNStage.
		
		?clinTNM roo:100241 ?clinTNMm.
		?clinTNMm rdf:type ?clinMStage.
	}
	
	{ 
		?disease roo:100287 ?pathTNM.
		?pathTNM rdf:type ncit:C48739.
		?pathTNM roo:100288 ?pathTNMt.
		?pathTNMt rdf:type ?pathTStage.
		
		?pathTNM roo:100286 ?pathTNMn.
		?pathTNMn rdf:type ?pathNStage.
		
		OPTIONAL {
			?pathTNM roo:100285 ?pathTNMm.
			?pathTNMm rdf:type ?pathMStage.
		}
	}
}