PREFIX icd:<http://purl.bioontology.org/ontology/ICD10/>
PREFIX ncit:<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX roo:<http://www.cancerdata.org/roo#>
PREFIX uo:<http://purl.obolibrary.org/obo/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
SELECT ?s ?p ?o {
  { ?s ?p ?o
  } MINUS
  {
    { SELECT ?PatientShape {
      ?PatientShape rdf:type ?o .
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape {
      ?PatientShape rdf:type ?o . FILTER ((?o = ncit:C16960))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c0) {
      ?PatientShape roo:ROO100001 ?o .
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape {
      ?PatientShape roo:ROO100001 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c1) {
        { SELECT ?PatientShape ?GenderShape {
          ?PatientShape roo:ROO100001 ?GenderShape . FILTER (true && (isIRI(?GenderShape) || isBlank(?GenderShape)))
        } }
        { SELECT ?GenderShape (COUNT(*) AS ?GenderShape_c0) {
          ?GenderShape rdf:type ?o .
        } GROUP BY ?GenderShape HAVING (COUNT(*)>=2)}
        { SELECT ?GenderShape (COUNT(*) AS ?GenderShape_c1) {
          ?GenderShape rdf:type ?o . FILTER ((?o = ncit:C28421 || ?o = ncit:C16576 || ?o = ncit:C20197))
        } GROUP BY ?GenderShape HAVING (COUNT(*)>=2)}
        FILTER (?GenderShape_c0 = ?GenderShape_c1)
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c0 = ?PatientShape_c1)
    OPTIONAL { ?PatientShape roo:ROO100001 ?PatientShape_GenderShape_ref0 . FILTER (true && (isIRI(?PatientShape_GenderShape_ref0) || isBlank(?PatientShape_GenderShape_ref0))) }
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c2) {
      ?PatientShape roo:ROO100003 ?o .
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape {
      ?PatientShape roo:ROO100003 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c3) {
        { SELECT ?PatientShape ?DiseaseShape {
          ?PatientShape roo:ROO100003 ?DiseaseShape . FILTER (true && (isIRI(?DiseaseShape) || isBlank(?DiseaseShape)))
        } }
        { SELECT ?DiseaseShape {
          ?DiseaseShape rdf:type ?o .
        } GROUP BY ?DiseaseShape HAVING (COUNT(*)=1)}
        { SELECT ?DiseaseShape {
          ?DiseaseShape rdf:type ?o . FILTER ((?o = icd:C20))
        } GROUP BY ?DiseaseShape HAVING (COUNT(*)=1)}
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c2 = ?PatientShape_c3)
    OPTIONAL { ?PatientShape roo:ROO100003 ?PatientShape_DiseaseShape_ref0 . FILTER (true && (isIRI(?PatientShape_DiseaseShape_ref0) || isBlank(?PatientShape_DiseaseShape_ref0))) }
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c4) {
      ?PatientShape roo:ROO100000 ?o .
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape {
      ?PatientShape roo:ROO100000 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c5) {
        { SELECT ?PatientShape ?AgeShape {
          ?PatientShape roo:ROO100000 ?AgeShape . FILTER (true && (isIRI(?AgeShape) || isBlank(?AgeShape)))
        } }
        { SELECT ?AgeShape {
          ?AgeShape rdf:type ?o .
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
        { SELECT ?AgeShape {
          ?AgeShape rdf:type ?o . FILTER ((?o = ncit:C25150))
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
        { SELECT ?AgeShape {
          ?AgeShape roo:ROO100008 ?o .
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
        { SELECT ?AgeShape {
          ?AgeShape roo:ROO100008 ?o . FILTER ((?o = uo:UO_0000036))
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
        { SELECT ?AgeShape {
          ?AgeShape roo:ROO100022 ?o .
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
        { SELECT ?AgeShape {
          ?AgeShape roo:ROO100022 ?o . FILTER (isLiteral(?o))
          . FILTER ( ?o > 18 ) 
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c4 = ?PatientShape_c5)
    OPTIONAL { ?PatientShape roo:ROO100000 ?PatientShape_AgeShape_ref0 . FILTER (true && (isIRI(?PatientShape_AgeShape_ref0) || isBlank(?PatientShape_AgeShape_ref0))) }
    { SELECT ?PatientShape {
      ?PatientShape roo:ROO100020 ?o .
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape {
      ?PatientShape roo:ROO100020 ?o . FILTER (isIRI(?o))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c6) {
      ?PatientShape roo:ROO100009 ?o .
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape {
      ?PatientShape roo:ROO100009 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c7) {
        { SELECT ?PatientShape ?VitalStatusShape {
          ?PatientShape roo:ROO100009 ?VitalStatusShape . FILTER (true && (isIRI(?VitalStatusShape) || isBlank(?VitalStatusShape)))
        } }
        { SELECT ?VitalStatusShape {
          ?VitalStatusShape rdf:type ?o .
        } GROUP BY ?VitalStatusShape HAVING (COUNT(*)=1)}
        { SELECT ?VitalStatusShape {
          ?VitalStatusShape rdf:type ?o . FILTER ((?o = ncit:C37987 || ?o = ncit:C28554))
        } GROUP BY ?VitalStatusShape HAVING (COUNT(*)=1)}
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c6 = ?PatientShape_c7)
    OPTIONAL { ?PatientShape roo:ROO100009 ?PatientShape_VitalStatusShape_ref0 . FILTER (true && (isIRI(?PatientShape_VitalStatusShape_ref0) || isBlank(?PatientShape_VitalStatusShape_ref0))) }
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c8) {
      ?PatientShape roo:ROO100007 ?o .
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape {
      ?PatientShape roo:ROO100007 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c9) {
        { SELECT ?PatientShape ?SurvivalInfoShape {
          ?PatientShape roo:ROO100007 ?SurvivalInfoShape . FILTER (true && (isIRI(?SurvivalInfoShape) || isBlank(?SurvivalInfoShape)))
        } }
        { SELECT ?SurvivalInfoShape {
          ?SurvivalInfoShape rdf:type ?o .
        } GROUP BY ?SurvivalInfoShape HAVING (COUNT(*)=1)}
        { SELECT ?SurvivalInfoShape {
          ?SurvivalInfoShape rdf:type ?o . FILTER ((?o = roo:ROO100036))
        } GROUP BY ?SurvivalInfoShape HAVING (COUNT(*)=1)}
        { SELECT ?SurvivalInfoShape {
          ?SurvivalInfoShape roo:ROO100008 ?o .
        } GROUP BY ?SurvivalInfoShape HAVING (COUNT(*)=1)}
        { SELECT ?SurvivalInfoShape {
          ?SurvivalInfoShape roo:ROO100008 ?o . FILTER ((?o = uo:UO_0000035))
        } GROUP BY ?SurvivalInfoShape HAVING (COUNT(*)=1)}
        { SELECT ?SurvivalInfoShape {
          ?SurvivalInfoShape roo:ROO100022 ?o .
        } GROUP BY ?SurvivalInfoShape HAVING (COUNT(*)=1)}
        { SELECT ?SurvivalInfoShape {
          ?SurvivalInfoShape roo:ROO100022 ?o . FILTER (isLiteral(?o))
          . FILTER ( ?o > 0 ) 
        } GROUP BY ?SurvivalInfoShape HAVING (COUNT(*)=1)}
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c8 = ?PatientShape_c9)
    OPTIONAL { ?PatientShape roo:ROO100007 ?PatientShape_SurvivalInfoShape_ref0 . FILTER (true && (isIRI(?PatientShape_SurvivalInfoShape_ref0) || isBlank(?PatientShape_SurvivalInfoShape_ref0))) }
    {
      { ?PatientShape rdf:type ?o . FILTER (true && (?o = ncit:C16960)) BIND (?PatientShape AS ?s) BIND (rdf:type AS ?p) } UNION
      { ?PatientShape roo:ROO100001 ?o . FILTER (true && (isIRI(?o) || isBlank(?o))) BIND (?PatientShape AS ?s) BIND (roo:ROO100001 AS ?p) } UNION
      {
        { ?PatientShape roo:ROO100001 ?PatientShape_GenderShape_ref0 . FILTER (true && (isIRI(?PatientShape_GenderShape_ref0) || isBlank(?PatientShape_GenderShape_ref0))) }
        {
          { ?PatientShape_GenderShape_ref0 rdf:type ?o . FILTER (true && (?o = ncit:C28421 || ?o = ncit:C16576 || ?o = ncit:C20197)) BIND (?PatientShape_GenderShape_ref0 AS ?s) BIND (rdf:type AS ?p) }
        }
      } UNION
      { ?PatientShape roo:ROO100003 ?o . FILTER (true && (isIRI(?o) || isBlank(?o))) BIND (?PatientShape AS ?s) BIND (roo:ROO100003 AS ?p) } UNION
      {
        { ?PatientShape roo:ROO100003 ?PatientShape_DiseaseShape_ref0 . FILTER (true && (isIRI(?PatientShape_DiseaseShape_ref0) || isBlank(?PatientShape_DiseaseShape_ref0))) }
        {
          { ?PatientShape_DiseaseShape_ref0 rdf:type ?o . FILTER (true && (?o = icd:C20)) BIND (?PatientShape_DiseaseShape_ref0 AS ?s) BIND (rdf:type AS ?p) }
        }
      } UNION
      { ?PatientShape roo:ROO100000 ?o . FILTER (true && (isIRI(?o) || isBlank(?o))) BIND (?PatientShape AS ?s) BIND (roo:ROO100000 AS ?p) } UNION
      {
        { ?PatientShape roo:ROO100000 ?PatientShape_AgeShape_ref0 . FILTER (true && (isIRI(?PatientShape_AgeShape_ref0) || isBlank(?PatientShape_AgeShape_ref0))) }
        {
          { ?PatientShape_AgeShape_ref0 rdf:type ?o . FILTER (true && (?o = ncit:C25150)) BIND (?PatientShape_AgeShape_ref0 AS ?s) BIND (rdf:type AS ?p) } UNION
          { ?PatientShape_AgeShape_ref0 roo:ROO100008 ?o . FILTER (true && (?o = uo:UO_0000036)) BIND (?PatientShape_AgeShape_ref0 AS ?s) BIND (roo:ROO100008 AS ?p) } UNION
          { ?PatientShape_AgeShape_ref0 roo:ROO100022 ?o . FILTER (true && isLiteral(?o)) BIND (?PatientShape_AgeShape_ref0 AS ?s) BIND (roo:ROO100022 AS ?p) }
        }
      } UNION
      { ?PatientShape roo:ROO100020 ?o . FILTER (true && isIRI(?o)) BIND (?PatientShape AS ?s) BIND (roo:ROO100020 AS ?p) } UNION
      { ?PatientShape roo:ROO100009 ?o . FILTER (true && (isIRI(?o) || isBlank(?o))) BIND (?PatientShape AS ?s) BIND (roo:ROO100009 AS ?p) } UNION
      {
        { ?PatientShape roo:ROO100009 ?PatientShape_VitalStatusShape_ref0 . FILTER (true && (isIRI(?PatientShape_VitalStatusShape_ref0) || isBlank(?PatientShape_VitalStatusShape_ref0))) }
        {
          { ?PatientShape_VitalStatusShape_ref0 rdf:type ?o . FILTER (true && (?o = ncit:C37987 || ?o = ncit:C28554)) BIND (?PatientShape_VitalStatusShape_ref0 AS ?s) BIND (rdf:type AS ?p) }
        }
      } UNION
      { ?PatientShape roo:ROO100007 ?o . FILTER (true && (isIRI(?o) || isBlank(?o))) BIND (?PatientShape AS ?s) BIND (roo:ROO100007 AS ?p) } UNION
      {
        { ?PatientShape roo:ROO100007 ?PatientShape_SurvivalInfoShape_ref0 . FILTER (true && (isIRI(?PatientShape_SurvivalInfoShape_ref0) || isBlank(?PatientShape_SurvivalInfoShape_ref0))) }
        {
          { ?PatientShape_SurvivalInfoShape_ref0 rdf:type ?o . FILTER (true && (?o = roo:ROO100036)) BIND (?PatientShape_SurvivalInfoShape_ref0 AS ?s) BIND (rdf:type AS ?p) } UNION
          { ?PatientShape_SurvivalInfoShape_ref0 roo:ROO100008 ?o . FILTER (true && (?o = uo:UO_0000035)) BIND (?PatientShape_SurvivalInfoShape_ref0 AS ?s) BIND (roo:ROO100008 AS ?p) } UNION
          { ?PatientShape_SurvivalInfoShape_ref0 roo:ROO100022 ?o . FILTER (true && isLiteral(?o)) BIND (?PatientShape_SurvivalInfoShape_ref0 AS ?s) BIND (roo:ROO100022 AS ?p) }
        }
      }
    }
  }
}
