PREFIX icd:<http://purl.bioontology.org/ontology/ICD10/>
PREFIX ncit:<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX roo:<http://www.cancerdata.org/roo/>
PREFIX uo:<http://purl.obolibrary.org/obo/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
ASK {

    { SELECT ?PatientShape {
      ?PatientShape a ?o . FILTER ((?o = ncit:C16960))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c1) {
      ?PatientShape roo:100018 ?o .
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape {
      ?PatientShape roo:100018 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c2) {
        { SELECT ?PatientShape ?GenderShape {
          ?PatientShape roo:100018 ?GenderShape . FILTER (true && (isIRI(?GenderShape) || isBlank(?GenderShape)))
        } }

        { SELECT ?GenderShape {
          ?GenderShape a ?o . FILTER ((?o = ncit:C28421))
        } GROUP BY ?GenderShape HAVING (COUNT(*)=1)}

        { SELECT ?GenderShape {
          ?GenderShape a ?o . FILTER ((?o = ncit:C16576 || ?o = ncit:C20197))
        } GROUP BY ?GenderShape HAVING (COUNT(*)=1)}
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c1 = ?PatientShape_c2)
    OPTIONAL { ?PatientShape roo:100018 ?PatientShape_GenderShape_ref0 . FILTER (true && (isIRI(?PatientShape_GenderShape_ref0) || isBlank(?PatientShape_GenderShape_ref0))) }
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c3) {
      ?PatientShape roo:100020 ?o .
    } GROUP BY ?PatientShape}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c4) {
      ?PatientShape roo:100020 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape}
    FILTER (?PatientShape_c3 = ?PatientShape_c4)
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c5) {
        { SELECT ?PatientShape ?DiseaseShape {
          ?PatientShape roo:100020 ?DiseaseShape . FILTER (true && (isIRI(?DiseaseShape) || isBlank(?DiseaseShape)))
        } }

        { SELECT ?DiseaseShape {
          ?DiseaseShape a ?o . FILTER ((?o = icd:C20))
        } GROUP BY ?DiseaseShape HAVING (COUNT(*)=1)}
        { SELECT ?DiseaseShape (COUNT(*) AS ?DiseaseShape_c1) {
          ?DiseaseShape roo:100243 ?o .
        } GROUP BY ?DiseaseShape HAVING (COUNT(*)=1)}
        { SELECT ?DiseaseShape {
          ?DiseaseShape roo:100243 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
        } GROUP BY ?DiseaseShape HAVING (COUNT(*)=1)}
        { SELECT ?DiseaseShape (COUNT(*) AS ?DiseaseShape_c2) {
            { SELECT ?DiseaseShape ?ClinicalTNMShape {
              ?DiseaseShape roo:100243 ?ClinicalTNMShape . FILTER (true && (isIRI(?ClinicalTNMShape) || isBlank(?ClinicalTNMShape)))
            } }

            { SELECT ?ClinicalTNMShape {
              ?ClinicalTNMShape a ?o . FILTER ((?o = ncit:C48881))
            } GROUP BY ?ClinicalTNMShape HAVING (COUNT(*)=1)}
            { SELECT ?ClinicalTNMShape (COUNT(*) AS ?ClinicalTNMShape_c1) {
              ?ClinicalTNMShape roo:100244 ?o .
            } GROUP BY ?ClinicalTNMShape HAVING (COUNT(*)=1)}
            { SELECT ?ClinicalTNMShape {
              ?ClinicalTNMShape roo:100244 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
            } GROUP BY ?ClinicalTNMShape HAVING (COUNT(*)=1)}
            { SELECT ?ClinicalTNMShape (COUNT(*) AS ?ClinicalTNMShape_c2) {
                { SELECT ?ClinicalTNMShape ?ClinTnmTShape {
                  ?ClinicalTNMShape roo:100244 ?ClinTnmTShape . FILTER (true && (isIRI(?ClinTnmTShape) || isBlank(?ClinTnmTShape)))
                } }

                { SELECT ?ClinTnmTShape {
                  ?ClinTnmTShape a ?o . FILTER ((?o = ncit:C48719 || ?o = ncit:C48720 || ?o = ncit:C48721 || ?o = ncit:C48722 || ?o = ncit:C48723 || ?o = ncit:C48724 || ?o = ncit:C48725 || ?o = ncit:C48726 || ?o = ncit:C48727 || ?o = ncit:C48728 || ?o = ncit:C48732 || ?o = ncit:C48737 || ?o = ncit:C48738))
                } GROUP BY ?ClinTnmTShape HAVING (COUNT(*)=1)}
            } GROUP BY ?ClinicalTNMShape }
            FILTER (?ClinicalTNMShape_c1 = ?ClinicalTNMShape_c2)
            OPTIONAL { ?ClinicalTNMShape roo:100244 ?ClinicalTNMShape_ClinTnmTShape_ref0 . FILTER (true && (isIRI(?ClinicalTNMShape_ClinTnmTShape_ref0) || isBlank(?ClinicalTNMShape_ClinTnmTShape_ref0))) }
            { SELECT ?ClinicalTNMShape (COUNT(*) AS ?ClinicalTNMShape_c3) {
              ?ClinicalTNMShape roo:100242 ?o .
            } GROUP BY ?ClinicalTNMShape}
            { SELECT ?ClinicalTNMShape (COUNT(*) AS ?ClinicalTNMShape_c4) {
              ?ClinicalTNMShape roo:100242 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
            } GROUP BY ?ClinicalTNMShape}
            FILTER (?ClinicalTNMShape_c3 = ?ClinicalTNMShape_c4)
            { SELECT ?ClinicalTNMShape (COUNT(*) AS ?ClinicalTNMShape_c5) {
                { SELECT ?ClinicalTNMShape ?ClinTnmNShape {
                  ?ClinicalTNMShape roo:100242 ?ClinTnmNShape . FILTER (true && (isIRI(?ClinTnmNShape) || isBlank(?ClinTnmNShape)))
                } }

                { SELECT ?ClinTnmNShape {
                  ?ClinTnmNShape a ?o . FILTER ((?o = ncit:C48705 || ?o = ncit:C48706 || ?o = ncit:C48706 || ?o = ncit:C48706 || ?o = ncit:C48706 || ?o = ncit:C48786 || ?o = ncit:C48786 || ?o = ncit:C48786 || ?o = ncit:C48786 || ?o = ncit:C48714 || ?o = ncit:C48714 || ?o = ncit:C48714 || ?o = ncit:C48714 || ?o = ncit:C48718))
                } GROUP BY ?ClinTnmNShape HAVING (COUNT(*)=1)}
            } GROUP BY ?ClinicalTNMShape }
            FILTER (?ClinicalTNMShape_c3 = ?ClinicalTNMShape_c5)
            OPTIONAL { ?ClinicalTNMShape roo:100242 ?ClinicalTNMShape_ClinTnmNShape_ref0 . FILTER (true && (isIRI(?ClinicalTNMShape_ClinTnmNShape_ref0) || isBlank(?ClinicalTNMShape_ClinTnmNShape_ref0))) }
            { SELECT ?ClinicalTNMShape (COUNT(*) AS ?ClinicalTNMShape_c6) {
              ?ClinicalTNMShape roo:100241 ?o .
            } GROUP BY ?ClinicalTNMShape}
            { SELECT ?ClinicalTNMShape (COUNT(*) AS ?ClinicalTNMShape_c7) {
              ?ClinicalTNMShape roo:100241 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
            } GROUP BY ?ClinicalTNMShape}
            FILTER (?ClinicalTNMShape_c6 = ?ClinicalTNMShape_c7)
            { SELECT ?ClinicalTNMShape (COUNT(*) AS ?ClinicalTNMShape_c8) {
                { SELECT ?ClinicalTNMShape ?ClinTnmMShape {
                  ?ClinicalTNMShape roo:100241 ?ClinTnmMShape . FILTER (true && (isIRI(?ClinTnmMShape) || isBlank(?ClinTnmMShape)))
                } }

                { SELECT ?ClinTnmMShape {
                  ?ClinTnmMShape a ?o . FILTER ((?o = ncit:C48699 || ?o = ncit:C48700 || ?o = ncit:C48701))
                } GROUP BY ?ClinTnmMShape HAVING (COUNT(*)=1)}
            } GROUP BY ?ClinicalTNMShape }
            FILTER (?ClinicalTNMShape_c6 = ?ClinicalTNMShape_c8)
            OPTIONAL { ?ClinicalTNMShape roo:100241 ?ClinicalTNMShape_ClinTnmMShape_ref0 . FILTER (true && (isIRI(?ClinicalTNMShape_ClinTnmMShape_ref0) || isBlank(?ClinicalTNMShape_ClinTnmMShape_ref0))) }
            FILTER (?ClinicalTNMShape_c1=0 && ?ClinicalTNMShape_c3=0 && ?ClinicalTNMShape_c6=0 || ?ClinicalTNMShape_c1>=1&&?ClinicalTNMShape_c1<=1 && ?ClinicalTNMShape_c3>=1&&?ClinicalTNMShape_c3<=1 && ?ClinicalTNMShape_c6>=1&&?ClinicalTNMShape_c6<=1)
        } GROUP BY ?DiseaseShape }
        FILTER (?DiseaseShape_c1 = ?DiseaseShape_c2)
        OPTIONAL { ?DiseaseShape roo:100243 ?DiseaseShape_ClinicalTNMShape_ref0 . FILTER (true && (isIRI(?DiseaseShape_ClinicalTNMShape_ref0) || isBlank(?DiseaseShape_ClinicalTNMShape_ref0))) }
        { SELECT ?DiseaseShape (COUNT(*) AS ?DiseaseShape_c3) {
          ?DiseaseShape roo:100287 ?o .
        } GROUP BY ?DiseaseShape}
        { SELECT ?DiseaseShape (COUNT(*) AS ?DiseaseShape_c4) {
          ?DiseaseShape roo:100287 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
        } GROUP BY ?DiseaseShape}
        FILTER (?DiseaseShape_c3 = ?DiseaseShape_c4)
        { SELECT ?DiseaseShape (COUNT(*) AS ?DiseaseShape_c5) {
            { SELECT ?DiseaseShape ?PathologicTNMShape {
              ?DiseaseShape roo:100287 ?PathologicTNMShape . FILTER (true && (isIRI(?PathologicTNMShape) || isBlank(?PathologicTNMShape)))
            } }

            { SELECT ?PathologicTNMShape {
              ?PathologicTNMShape a ?o . FILTER ((?o = ncit:C48739))
            } GROUP BY ?PathologicTNMShape HAVING (COUNT(*)=1)}
            { SELECT ?PathologicTNMShape (COUNT(*) AS ?PathologicTNMShape_c1) {
              ?PathologicTNMShape roo:100288 ?o .
            } GROUP BY ?PathologicTNMShape HAVING (COUNT(*)=1)}
            { SELECT ?PathologicTNMShape {
              ?PathologicTNMShape roo:100288 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
            } GROUP BY ?PathologicTNMShape HAVING (COUNT(*)=1)}
            { SELECT ?PathologicTNMShape (COUNT(*) AS ?PathologicTNMShape_c2) {
                { SELECT ?PathologicTNMShape ?PathTnmTShape {
                  ?PathologicTNMShape roo:100288 ?PathTnmTShape . FILTER (true && (isIRI(?PathTnmTShape) || isBlank(?PathTnmTShape)))
                } }

                { SELECT ?PathTnmTShape {
                  ?PathTnmTShape a ?o . FILTER ((?o = ncit:C48719 || ?o = ncit:C48720 || ?o = ncit:C48721 || ?o = ncit:C48722 || ?o = ncit:C48723 || ?o = ncit:C48724 || ?o = ncit:C48725 || ?o = ncit:C48726 || ?o = ncit:C48727 || ?o = ncit:C48728 || ?o = ncit:C48732 || ?o = ncit:C48737 || ?o = ncit:C48738))
                } GROUP BY ?PathTnmTShape HAVING (COUNT(*)=1)}
            } GROUP BY ?PathologicTNMShape }
            FILTER (?PathologicTNMShape_c1 = ?PathologicTNMShape_c2)
            OPTIONAL { ?PathologicTNMShape roo:100288 ?PathologicTNMShape_PathTnmTShape_ref0 . FILTER (true && (isIRI(?PathologicTNMShape_PathTnmTShape_ref0) || isBlank(?PathologicTNMShape_PathTnmTShape_ref0))) }
            { SELECT ?PathologicTNMShape (COUNT(*) AS ?PathologicTNMShape_c3) {
              ?PathologicTNMShape roo:100286 ?o .
            } GROUP BY ?PathologicTNMShape}
            { SELECT ?PathologicTNMShape (COUNT(*) AS ?PathologicTNMShape_c4) {
              ?PathologicTNMShape roo:100286 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
            } GROUP BY ?PathologicTNMShape}
            FILTER (?PathologicTNMShape_c3 = ?PathologicTNMShape_c4)
            { SELECT ?PathologicTNMShape (COUNT(*) AS ?PathologicTNMShape_c5) {
                { SELECT ?PathologicTNMShape ?PathTnmNShape {
                  ?PathologicTNMShape roo:100286 ?PathTnmNShape . FILTER (true && (isIRI(?PathTnmNShape) || isBlank(?PathTnmNShape)))
                } }

                { SELECT ?PathTnmNShape {
                  ?PathTnmNShape a ?o . FILTER ((?o = ncit:C48705 || ?o = ncit:C48706 || ?o = ncit:C48706 || ?o = ncit:C48706 || ?o = ncit:C48706 || ?o = ncit:C48786 || ?o = ncit:C48786 || ?o = ncit:C48786 || ?o = ncit:C48786 || ?o = ncit:C48714 || ?o = ncit:C48714 || ?o = ncit:C48714 || ?o = ncit:C48714 || ?o = ncit:C48718))
                } GROUP BY ?PathTnmNShape HAVING (COUNT(*)=1)}
            } GROUP BY ?PathologicTNMShape }
            FILTER (?PathologicTNMShape_c3 = ?PathologicTNMShape_c5)
            OPTIONAL { ?PathologicTNMShape roo:100286 ?PathologicTNMShape_PathTnmNShape_ref0 . FILTER (true && (isIRI(?PathologicTNMShape_PathTnmNShape_ref0) || isBlank(?PathologicTNMShape_PathTnmNShape_ref0))) }
            { SELECT ?PathologicTNMShape (COUNT(*) AS ?PathologicTNMShape_c6) {
              ?PathologicTNMShape roo:100285 ?o .
            } GROUP BY ?PathologicTNMShape}
            { SELECT ?PathologicTNMShape (COUNT(*) AS ?PathologicTNMShape_c7) {
              ?PathologicTNMShape roo:100285 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
            } GROUP BY ?PathologicTNMShape}
            FILTER (?PathologicTNMShape_c6 = ?PathologicTNMShape_c7)
            { SELECT ?PathologicTNMShape (COUNT(*) AS ?PathologicTNMShape_c8) {
                { SELECT ?PathologicTNMShape ?PathTnmMShape {
                  ?PathologicTNMShape roo:100285 ?PathTnmMShape . FILTER (true && (isIRI(?PathTnmMShape) || isBlank(?PathTnmMShape)))
                } }

                { SELECT ?PathTnmMShape {
                  ?PathTnmMShape a ?o . FILTER ((?o = ncit:C48699 || ?o = ncit:C48700 || ?o = ncit:C48701))
                } GROUP BY ?PathTnmMShape HAVING (COUNT(*)=1)}
            } GROUP BY ?PathologicTNMShape }
            FILTER (?PathologicTNMShape_c6 = ?PathologicTNMShape_c8)
            OPTIONAL { ?PathologicTNMShape roo:100285 ?PathologicTNMShape_PathTnmMShape_ref0 . FILTER (true && (isIRI(?PathologicTNMShape_PathTnmMShape_ref0) || isBlank(?PathologicTNMShape_PathTnmMShape_ref0))) }
            FILTER (?PathologicTNMShape_c1=0 && ?PathologicTNMShape_c3=0 && ?PathologicTNMShape_c6=0 || ?PathologicTNMShape_c1>=1&&?PathologicTNMShape_c1<=1 && ?PathologicTNMShape_c3>=1&&?PathologicTNMShape_c3<=1 && ?PathologicTNMShape_c6>=1&&?PathologicTNMShape_c6<=1)
        } GROUP BY ?DiseaseShape }
        FILTER (?DiseaseShape_c3 = ?DiseaseShape_c5)
        OPTIONAL { ?DiseaseShape roo:100287 ?DiseaseShape_PathologicTNMShape_ref0 . FILTER (true && (isIRI(?DiseaseShape_PathologicTNMShape_ref0) || isBlank(?DiseaseShape_PathologicTNMShape_ref0))) }
        FILTER (?DiseaseShape_c1=0 && ?DiseaseShape_c3=0 || ?DiseaseShape_c1>=1&&?DiseaseShape_c1<=1 && ?DiseaseShape_c3>=1&&?DiseaseShape_c3<=1)
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c3 = ?PatientShape_c5)
    OPTIONAL { ?PatientShape roo:100020 ?PatientShape_DiseaseShape_ref0 . FILTER (true && (isIRI(?PatientShape_DiseaseShape_ref0) || isBlank(?PatientShape_DiseaseShape_ref0))) }
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c6) {
      ?PatientShape roo:100000 ?o .
    } GROUP BY ?PatientShape}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c7) {
      ?PatientShape roo:100000 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape}
    FILTER (?PatientShape_c6 = ?PatientShape_c7)
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c8) {
        { SELECT ?PatientShape ?AgeShape {
          ?PatientShape roo:100000 ?AgeShape . FILTER (true && (isIRI(?AgeShape) || isBlank(?AgeShape)))
        } }

        { SELECT ?AgeShape {
          ?AgeShape a ?o . FILTER ((?o = ncit:C25150))
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}

        { SELECT ?AgeShape {
          ?AgeShape roo:100027 ?o . FILTER ((?o = uo:UO_0000036))
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}

        { SELECT ?AgeShape {
          ?AgeShape roo:100042 ?o . FILTER (isLiteral(?o))
          . FILTER ( ?o > 18 ) 
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c6 = ?PatientShape_c8)
    OPTIONAL { ?PatientShape roo:100000 ?PatientShape_AgeShape_ref0 . FILTER (true && (isIRI(?PatientShape_AgeShape_ref0) || isBlank(?PatientShape_AgeShape_ref0))) }
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c9) {
      ?PatientShape roo:100039 ?o .
    } GROUP BY ?PatientShape}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c10) {
      ?PatientShape roo:100039 ?o . FILTER (isIRI(?o))
    } GROUP BY ?PatientShape}
    FILTER (?PatientShape_c9 = ?PatientShape_c10)
    FILTER (?PatientShape_c1=0 && ?PatientShape_c3=0 && ?PatientShape_c6=0 && ?PatientShape_c9=0 || ?PatientShape_c1>=1&&?PatientShape_c1<=1 && ?PatientShape_c3>=1&&?PatientShape_c3<=1 && ?PatientShape_c6>=1&&?PatientShape_c6<=1 && ?PatientShape_c9>=1&&?PatientShape_c9<=1)
}