PREFIX icd:<http://purl.bioontology.org/ontology/ICD10/>
PREFIX ncit:<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX roo:<http://www.cancerdata.org/roo/>
PREFIX uo:<http://purl.obolibrary.org/obo/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
ASK {
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c0) {
      ?PatientShape a ?o .
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape {
      ?PatientShape a ?o . FILTER ((?o = ncit:C16960))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c1) {
      ?PatientShape roo:100018 ?o .
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape {
      ?PatientShape roo:100018 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape HAVING (COUNT(*)=1)}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c2) {
        { SELECT ?PatientShape ?GenderShape {
          ?PatientShape roo:100018 ?GenderShape . FILTER (true && (isIRI(?GenderShape) || isBlank(?GenderShape)))
        } }
        { SELECT ?GenderShape (COUNT(*) AS ?GenderShape_c0) {
          ?GenderShape a ?o .
        } GROUP BY ?GenderShape HAVING (COUNT(*)=1)}
        { SELECT ?GenderShape {
          ?GenderShape a ?o . FILTER ((?o = ncit:C28421))
        } GROUP BY ?GenderShape HAVING (COUNT(*)=1)}
        { SELECT ?GenderShape (COUNT(*) AS ?GenderShape_c1) {
          ?GenderShape a ?o .
        } GROUP BY ?GenderShape HAVING (COUNT(*)=1)}
        { SELECT ?GenderShape {
          ?GenderShape a ?o . FILTER ((?o = ncit:C16576 || ?o = ncit:C20197))
        } GROUP BY ?GenderShape HAVING (COUNT(*)=1)}
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c1 = ?PatientShape_c2)
    OPTIONAL { ?PatientShape roo:100018 ?PatientShape_GenderShape_ref0 . FILTER (true && (isIRI(?PatientShape_GenderShape_ref0) || isBlank(?PatientShape_GenderShape_ref0))) }
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c3) {
      ?PatientShape roo:100020 ?o .
    } GROUP BY ?PatientShape}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c4) {
      ?PatientShape roo:100020 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape}
    FILTER (?PatientShape_c3 = ?PatientShape_c4)
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c5) {
        { SELECT ?PatientShape ?DiseaseShape {
          ?PatientShape roo:100020 ?DiseaseShape . FILTER (true && (isIRI(?DiseaseShape) || isBlank(?DiseaseShape)))
        } }
        { SELECT ?DiseaseShape (COUNT(*) AS ?DiseaseShape_c0) {
          ?DiseaseShape a ?o .
        } GROUP BY ?DiseaseShape HAVING (COUNT(*)=1)}
        { SELECT ?DiseaseShape {
          ?DiseaseShape a ?o . FILTER ((?o = icd:C20))
        } GROUP BY ?DiseaseShape HAVING (COUNT(*)=1)}
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c3 = ?PatientShape_c5)
    OPTIONAL { ?PatientShape roo:100020 ?PatientShape_DiseaseShape_ref0 . FILTER (true && (isIRI(?PatientShape_DiseaseShape_ref0) || isBlank(?PatientShape_DiseaseShape_ref0))) }
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c6) {
      ?PatientShape roo:100000 ?o .
    } GROUP BY ?PatientShape}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c7) {
      ?PatientShape roo:100000 ?o . FILTER ((isIRI(?o) || isBlank(?o)))
    } GROUP BY ?PatientShape}
    FILTER (?PatientShape_c6 = ?PatientShape_c7)
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c8) {
        { SELECT ?PatientShape ?AgeShape {
          ?PatientShape roo:100000 ?AgeShape . FILTER (true && (isIRI(?AgeShape) || isBlank(?AgeShape)))
        } }
        { SELECT ?AgeShape (COUNT(*) AS ?AgeShape_c0) {
          ?AgeShape a ?o .
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
        { SELECT ?AgeShape {
          ?AgeShape a ?o . FILTER ((?o = ncit:C25150))
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
        { SELECT ?AgeShape (COUNT(*) AS ?AgeShape_c1) {
          ?AgeShape roo:100027 ?o .
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
        { SELECT ?AgeShape {
          ?AgeShape roo:100027 ?o . FILTER ((?o = uo:UO_0000036))
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
        { SELECT ?AgeShape (COUNT(*) AS ?AgeShape_c2) {
          ?AgeShape roo:100042 ?o .
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
        { SELECT ?AgeShape {
          ?AgeShape roo:100042 ?o . FILTER (isLiteral(?o))
          . FILTER ( ?o > 18 ) 
        } GROUP BY ?AgeShape HAVING (COUNT(*)=1)}
    } GROUP BY ?PatientShape }
    FILTER (?PatientShape_c6 = ?PatientShape_c8)
    OPTIONAL { ?PatientShape roo:100000 ?PatientShape_AgeShape_ref0 . FILTER (true && (isIRI(?PatientShape_AgeShape_ref0) || isBlank(?PatientShape_AgeShape_ref0))) }
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c9) {
      ?PatientShape roo:100039 ?o .
    } GROUP BY ?PatientShape}
    { SELECT ?PatientShape (COUNT(*) AS ?PatientShape_c10) {
      ?PatientShape roo:100039 ?o . FILTER (isIRI(?o))
    } GROUP BY ?PatientShape}
    FILTER (?PatientShape_c9 = ?PatientShape_c10)
    FILTER (?PatientShape_c1=0 && ?PatientShape_c3=0 && ?PatientShape_c6=0 && ?PatientShape_c9=0 || ?PatientShape_c1>=1&&?PatientShape_c1<=1 && ?PatientShape_c3>=1&&?PatientShape_c3<=1 && ?PatientShape_c6>=1&&?PatientShape_c6<=1 && ?PatientShape_c9>=1&&?PatientShape_c9<=1)
}